# Generated by Django 4.0.2 on 2022-03-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techfest',
            name='logo',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(null=True, upload_to='event/sponsors_images'),
        ),
        migrations.AddField(
            model_name='studentcouncilmembers',
            name='image',
            field=models.ImageField(null=True, upload_to='event/student_council_images'),
        ),
        migrations.AddField(
            model_name='techfest',
            name='college_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='techfest',
            name='fest_video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='techfest',
            name='society_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='techfest',
            name='university_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='event/videos'),
        ),
    ]
