# Generated by Django 4.0.2 on 2022-02-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('name',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='speakers',
            options={'ordering': ('name',), 'verbose_name': 'Speaker', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='sponsors',
            options={'ordering': ('name',), 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='studentcoordinators',
            options={'ordering': ('name',), 'verbose_name': 'Student Coordinator', 'verbose_name_plural': 'Student Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='studentcouncilmembers',
            options={'ordering': ('name',), 'verbose_name': 'Student Council', 'verbose_name_plural': 'Student Council Members'},
        ),
        migrations.AlterModelOptions(
            name='teachercoordinators',
            options={'ordering': ('name',), 'verbose_name': 'Teacher Coordinator', 'verbose_name_plural': 'Teacher Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='techfest',
            options={'ordering': ('name',), 'verbose_name': 'Tech Fest', 'verbose_name_plural': 'Tech Fest'},
        ),
    ]
