# Generated by Django 4.0.2 on 2022-02-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_events_options_alter_speakers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentcouncilmembers',
            name='image',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='event/images'),
        ),
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(null=True, upload_to='event/speakers_images'),
        ),
        migrations.AlterField(
            model_name='studentcoordinators',
            name='image',
            field=models.ImageField(null=True, upload_to='event/student_coordinators_images'),
        ),
        migrations.AlterField(
            model_name='teachercoordinators',
            name='image',
            field=models.ImageField(null=True, upload_to='event/teacher_coordinator_images'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.ImageField(null=True, upload_to='event/videos'),
        ),
    ]
