# Generated by Django 4.0.2 on 2022-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_techfest_logo_sponsors_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfest',
            name='short_description',
            field=models.CharField(max_length=600),
        ),
    ]
