# Generated by Django 4.0.2 on 2022-03-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_techfest_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='techfest',
            name='fest_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
