# Generated by Django 4.0.2 on 2022-04-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_events_event_image_events_event_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcouncilmembers',
            name='is_design_team',
            field=models.BooleanField(default=False),
        ),
    ]
