# Generated by Django 4.0.2 on 2022-04-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_studentcouncilmembers_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercoordinators',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
