# Generated by Django 4.0.2 on 2022-04-21 19:06

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_teachercoordinators_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsTimeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Event TimeLine',
                'verbose_name_plural': 'Event TimeLine',
            },
        ),
    ]
