# Generated by Django 4.0.2 on 2022-04-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_eventstimeline_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstimeline',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
