# Generated by Django 4.0.2 on 2022-04-21 21:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_eventstimeline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='event',
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='rules',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
