# Generated by Django 4.0.2 on 2022-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_videos_event_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
